language: node_js
node_js:
  - 0.6
before_script:
  - "export DISPLAY=:99.0" 
  - "sh -e /etc/init.d/xvfb start"
  - npm install express
  - env PORT=1337 sudo node js/test/serve/index.js &
  - sleep 5
script: phantomjs js/test/serve/run-qunit.js "http://localhost:1337/index.html" &&
  phantomjs js/test/serve/run-qunit.js "http://localhost:1337/js/test/index.html"