language: node_js
node_js:
  - 0.6
before_script:
  - npm install express
  - env PORT=80 node js/test/server/index.js &
  - sleep 5
script: 
  - phantomjs js/test/server/run-qunit.js "http://localhost:80/index.html"
  - phantomjs js/test/server/run-qunit.js "http://localhost:80/js/test/index.html"